### ISSUE TITLE
broken on 1.3.x, update to support latest ng

### ISSUE THREAD

**Issue by robertbaker** [Luegg/angularjs-scroll-glue#29]
Please make it work for ng 1.3.x and 1.4.x

**Comment by robertbaker** [comment]
@Luegg Any idea why it doesn't work on 1.3.x?

**Comment by JonasPriest** [comment]
That would be really nice! Really seems to be broken for 1.3.x in my app, too. Nice work thou

**Comment by Sshuichi** [comment]
+1

**Comment by char0n** [comment]
@robertbaker What do you mean by broken and what do you mean by ng 1.3.18?
Latest release of angular is 1.3.16 which was released 5 days ago and scroll-glue works there.

However, I experience some sort of laziness of scroll-glue manifested by gluing the scroller after X seconds and not immediately. It is caused by the fact that $digest cycle is sometimes triggered very infrequently, sometimes after 6 seconds. 

Somebody experiencing the same issue ? Affected are all browsers.

**Comment by robertbaker** [comment]
It's broken on ng (angular) 1.3.16 and 1.4.x

**Comment by char0n** [comment]
@robertbaker What does broken mean for you ? I imagine branch of tree to be broken... Provide details please...

Except for the behavior I described, I see no other faulty behavior.

**Comment by robertbaker** [comment]
Broken as it does not work at all.

Fork the demo fiddle. Change the angular srcs to 1.4 and it won't work.

**Comment by robertbaker** [comment]
http://plnkr.co/edit/KsUSblFZP6tuVO7UAQMH?p=preview

**Comment by char0n** [comment]
Ok so to be crystal clear,

I can confirm that  it works on 1.3.16 but has a 'lazy' problem I described.

Your plnkr confirms that it is not working on 1.4 branch at all.

Thanks
